[package]
name = "dicom-map-py"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Python bindings for dicom-map"

[lib]
name = "dicom_map"
crate-type = ["cdylib"]

[dependencies]
dicom-map = { path = "../dicom-map" }
pyo3 = { version = "0.22", features = ["extension-module"] }
