[package]
name = "dicom-map-py"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
readme = "README.md"
description = "Python bindings for dicom-map"

[lib]
name = "_dicom_map"
crate-type = ["cdylib"]

[dependencies]
dicom-map = { path = "../dicom-map", version = "0.2.3" }
pyo3 = { version = "0.22", features = [
    "extension-module",
    "generate-import-lib",
] }
